### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by simplygreatwork** [jimf/uparse#2]
Hi Jim,

I've used this library in the past to parse s-expressions for webassembly wat files. I also made a parser which used split for statements (newline or semicolon) and between for brackets/blocks. I've made a lot of progress implementing split and between.

But currently, I'm investigating parsing based on indentation. So that any line which is indented under a parent would become a child of the parent. Do you think that this is possible with uparse as it currently exists? I realize that this question might be beyond scope of support for this excellent tiny library. But I just wanted to ask if you have any thoughts.

**Comment by jimf** [comment]
Hmm. I feel myself getting [nerd-sniped](https://explainxkcd.com/wiki/index.php/356:_Nerd_Sniping). I don't have the time to look into this at the moment, but I'm honestly not sure. I've implemented a whitespace-sensitive parser in the past, but it was with recursive descent and not parser combinators. That said, a parser combinator solution _should_ be able to get the job done. I'm just not 100% sure if this library has everything needed.

For a breadcrumb, the [Nim language manual](https://nim-lang.org/docs/manual.html#lexical-analysis-indentation) was very helpful for me in implementing a recursive descent solution:

> Nim's standard grammar describes an indentation sensitive language. This means that all the control structures are recognized by indentation. Indentation consists only of spaces; tabulators are not allowed.
>
> The indentation handling is implemented as follows: The lexer annotates the following token with the preceding number of spaces; indentation is not a separate token. This trick allows parsing of Nim with only 1 token of lookahead.
>
> The parser uses a stack of indentation levels: the stack consists of integers counting the spaces. The indentation information is queried at strategic places in the parser but ignored otherwise: The pseudo terminal IND{>} denotes an indentation that consists of more spaces than the entry at the top of the stack; IND{=} an indentation that has the same number of spaces. DED is another pseudo terminal that describes the action of popping a value from the stack, IND{>} then implies to push onto the stack.
>
> With this notation we can now easily define the core of the grammar: A block of statements

**Comment by simplygreatwork** [comment]
Hi Jim,

Thanks for your response. No nerd-sniping intended. I'm close to having this working and I'll post an small example. I know this library is not even a major focus for you. I think the only thing I might have to tweak to somehow passing indentation levels through p.ref. Peace.

**Comment by simplygreatwork** [comment]
I did implement an s-expression [parser with indentation](https://github.com/simplygreatwork/sweet-webassembly/blob/master/parser/configurations/sexpressions-implicit.js) which includes support to implicitly define nested expressions. The main change I made to my copy of uparse was to p.ref to allow passing of values (indentation levels). Posting this here as one example of how to use uparse.
